apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyteadmin
  namespace: flyte
spec:
  template:
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:10.1
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c',
          'until pg_isready -h cloudsqlproxy -p 5432;
          do echo waiting for database; sleep 2; done;']
      - name: run-migrations
        volumeMounts:
        - name: db-user-pass
          mountPath: /etc/gcp
      # uncomment to seed (pre-create) a few projects into flyteadmin
      # - name: seed-projects
      #   image: docker.io/lyft/flyteadmin:v0.2.1
      #   imagePullPolicy: IfNotPresent
      #   command: ["flyteadmin", "--logtostderr", "--config", "/etc/flyte/config/flyteadmin_config.yaml",
      #             "migrate", "seed-projects", "flytesnacks", "flytetester"]
      #   volumeMounts:
      #   - name: config-volume
      #     mountPath: /etc/flyte/config
      #   - name: db-user-pass
      #     mountPath: /etc/gcp
      containers:
      - name: flyteadmin
        volumeMounts:
        - name: db-user-pass
          mountPath: /etc/gcp
        resources:
          limits:
            memory: "200Mi"
            cpu: "1"
            ephemeral-storage: "100Mi"
      volumes:
        - name: db-user-pass
          secret:
            secretName: db-user-pass
