apiVersion: apps/v1
kind: Deployment
metadata:
  name: flytepropeller
  namespace: flyte
spec:
  template:
    spec:
      containers:
      - name: flytepropeller
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1"
            ephemeral-storage: "1000Mi"
