docker-registry:
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePort: 30000

flyte-binary:
  networking:
    host: true
  image:
    fqn: "ghcr.io/flyteorg/flyte-sandbox:flytebinary_1007"
  storage:
    metadataContainer: flyte-sandbox
    userDataContainer: flyte-sandbox
    type: minio
    region: my-region
  database:
    port: 30001
    username: postgres
    host: 127.0.0.1
    dbname: flyteadmin
    password: postgres
  logger:
    level: 1

kubernetes-dashboard:
  extraArgs:
    - --enable-insecure-login
    - --enable-skip-login
  protocolHttp: true
  service:
    externalPort: 80
  rbac:
    create: true
    clusterRoleMetrics: false
    clusterReadOnlyRole: true

minio:
  auth:
    rootUser: minio
    rootPassword: miniostorage
  defaultBuckets: flyte-sandbox
  extraEnvVars:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: http://localhost:30080/minio
  service:
    type: NodePort
    nodePorts:
      api: 30002
  persistence:
    enabled: true
    storageClass: local-path

postgresql:
  auth:
    postgresPassword: postgres
  shmVolume:
    enabled: false
  primary:
    service:
      type: NodePort
      nodePorts:
        postgresql: 30001
    persistence:
      enabled: true
      storageClass: local-path
