docker-registry:
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePort: 30000

# flyte-binary:

kubernetes-dashboard:
  extraArgs:
    - --enable-insecure-login
    - --enable-skip-login
  protocolHttp: true
  service:
    externalPort: 80
  rbac:
    create: true
    clusterRoleMetrics: false
    clusterReadOnlyRole: true

minio:
  auth:
    rootUser: minio
    rootPassword: miniostorage
  defaultBuckets: flyte-sandbox
  extraEnvVars:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: http://localhost:30080/minio
  service:
    type: NodePort
    nodePorts:
      api: 30002
  persistence:
    enabled: false

postgresql:
  shmVolume:
    enabled: false
  primary:
    extraEnvVars:
      - name: POSTGRES_HOST_AUTH_METHOD
        value: trust
    service:
      type: NodePort
      nodePorts:
        postgresql: 30001
    persistence:
      enabled: false
