propeller:
  rawoutput-prefix: "s3://{{ .Values.storage.userDataContainer }}/data/"
  create-flyteworkflow-crd: true
webhook:
  certDir: /var/run/flyte/certs
  localCert: true
tasks:
  task-plugins:
    enabled-plugins:
      - container
      - sidecar
      - K8S-ARRAY
    default-for-task-types:
      - container: container
      - container_array: K8S-ARRAY
database:
  postgres:
    port: {{ .Values.database.port }}
    username: {{ .Values.database.username }}
    host: {{ .Values.database.host }}
    dbname: {{ .Values.database.dbname }}
    options: "sslmode=disable"
    {{- if .Values.database.password }}
    {{- include "flyte-binary.database.secretpathconfig" . | nindent 4 }}
    {{- end }}
storage:
  type: {{ .Values.storage.type }}
  connection:
    region: {{ .Values.storage.region }}
    {{- if eq .Values.storage.type "minio" }}
    {{- include "flyte-binary.minioExtraConnectionSettings" . | nindent 4 }}
    {{- end }}
  cache:
    max_size_mbs: 10
    target_gc_percent: 100
  container: "{{ .Values.storage.metadataContainer }}"
logger:
  show-source: true
  level: {{ .Values.logger.level }}
admin:
  endpoint: localhost:8089
  insecure: true
plugins:
  # All k8s plugins default configuration
  k8s:
    inject-finalizer: true
    default-env-vars:
      - AWS_METADATA_SERVICE_TIMEOUT: 5
      - AWS_METADATA_SERVICE_NUM_ATTEMPTS: 20
      {{- if eq .Values.storage.type "minio" }}
      {{- include "flyte-binary.minioExtraEnvVars" . | nindent 6 }}
      {{- end }}
  # Logging configuration
  # Escape Helm templating because admin will template these later
  logs:
    kubernetes-enabled: true
    kubernetes-template-uri:
        {{`"http://localhost:30080/kubernetes-dashboard/#/log/{{ .namespace }}/{{ .podName }}/pod?namespace={{ .namespace }}"`}}
  k8s-array:
    logs:
      config:
        kubernetes-enabled: true
        kubernetes-template-uri: 
            {{`"http://localhost:30080/kubernetes-dashboard/#/log/{{ .namespace }}/{{ .podName }}/pod?namespace={{ .namespace }}"`}}
catalog-cache:
  endpoint: localhost:8081
  insecure: true
  type: datacatalog
namespace_mapping:
  template: {{`"{{ project }}-{{ domain }}"`}}
