networking:
  host: true

image:
  fqn: "ghcr.io/flyteorg/flyte-sandbox:flytebinary_1007"

storage:
  metadataContainer: my-s3-bucket
  userDataContainer: my-s3-bucket
  type: minio
  region: my-region

database:
  port: 5432
  username: postgres
  host: 127.0.0.1
  dbname: flyteadmin
  password: ""

logger:
  level: 1

paths:
  # Specify full path to Flyte binary config file here if being provided externally
  externalFlyteConfig: ""

# Need to add an aws section for IAM role annotation

proxy:
  enabled: false
