apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: flyteworkflows.flyte.lyft.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: flyte.lyft.com
  # version name to use for REST API: /apis/<group>/<version>
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  # either Namespaced or Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: flyteworkflows
    # singular name to be used as an alias on the CLI and for display
    singular: flyteworkflow
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: FlyteWorkflow
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - fly
  scope: Namespaced
