project_name: flyte
builds:
  - skip: true
release:
  github:
    owner: flyteorg
    name: flyte
  draft: false
  prerelease: auto
  discussion_category_name: General
  name_template: "{{.ProjectName}}-v{{.Version}}"
  disable: false
  extra_files:
    - glob: ./release/*