apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: flyte-sandbox-mysql
    app.kubernetes.io/name: flyte-sandbox-mysql
  name: flyte-sandbox-mysql
  namespace: flyte
spec:
  ports:
  - name: mysqlodbc
    nodePort: 30003
    port: 3306
    protocol: TCP
  selector:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: flyte-sandbox-mysql
    app.kubernetes.io/name: flyte-sandbox-mysql
  type: NodePort
