apiVersion: apps/v1
kind: Deployment
metadata:
    name: proxy
    labels:
        app: proxy
spec:
    selector:
        matchLabels:
            app: proxy
    template:
        metadata:
            labels:
                app: proxy
        spec:
            containers:
                - name: proxy
                  image: envoyproxy/envoy:v1.23-latest
                  imagePullPolicy: IfNotPresent
                  args:
                      - envoy
                      - -c /etc/envoy/config.yaml
                  ports:
                      - name: admin
                        containerPort: 9901
                      - name: http
                        containerPort: 8000
                  volumeMounts:
                      - name: config-volume
                        mountPath: /etc/envoy
            volumes:
                - name: config-volume
                  configMap:
                      name: flyteproxyconfig
