apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
  name: flyte-test-bucket
spec:
  bucketPolicyOnly: true
  versioning:
    enabled: false
