apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyte-pod-webhook
  namespace: flyte
spec:
  template:
    spec:
      containers:
        - name: webhook
          volumeMounts:
            - name: sample-secrets
              mountPath: /etc/secrets/user-info
              readOnly: true
      volumes:
        - name: sample-secrets
          secret:
            secretName: user-info
