name: "Documentation"
description: "Report an issue or suggest an improvement for Flyte docs"
title: "[Documentation]"
labels: [documentation,untriaged]
body:
  - type: textarea
    id: issue-description
    validations:
      required: true
    attributes:
      label: "Description"
      description: "Describe the documentation update"
      placeholder: "The issues/changes ..."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      options:
        - label: "Are you sure this issue hasn't been raised already?"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      options:
        - label: "Have you read the [Code of Conduct]( https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md)?"
          required: true
