name: Flytectl Feature request
description: Suggest a feature for flytectl
title: "[Flytectl Feature]"
labels: enhancement, untriaged, flytectl
body:
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "Describe the feature/command for flytectl"
      description: "A clear and concise description of what the problem is. "
      placeholder: "I'm frustrated when [...] OR this feature can be a cool addition because [...] OR this feature can simplify [...] use case."
  - type: textarea
    id: example
    validations:
      required: true
    attributes:
      label: "Provide a possible output or UX example"
      description: " A clear and concise description of what you want to happen or achieve."
      placeholder: "This feature can help implement or resolve [...]"
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      options:
        - label: "Are you sure this issue hasn't been raised already?"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      options:
        - label: "Have you read the [Code of Conduct]( https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md)?"
          required: true
