flyteadmin:
  enabled: false

cluster_resource_manager:
  enabled: false
  config:
    cluster_resources:
      standaloneDeployment: false

workflow_scheduler:
  enabled: false

flytescheduler:
  enabled: false

datacatalog:
  enabled: false

flyteconsole:
  enabled: false
