{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flyte-binary.fullname" . }}-cluster-role-binding
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "flyte-binary.renderTemplate" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.labels }}
    {{- include "flyte-binary.renderTemplate" (dict "value" .Values.rbac.labels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "flyte-binary.renderTemplate" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.annotations }}
    {{- include "flyte-binary.renderTemplate" (dict "value" .Values.rbac.annotations "context" $) | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "flyte-binary.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "flyte-binary.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
