{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "flyte-binary.fullname" . }}-cluster-role
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "flyte-binary.renderTemplate" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.labels }}
    {{- include "flyte-binary.renderTemplate" (dict "value" .Values.rbac.labels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "flyte-binary.renderTemplate" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.annotations }}
    {{- include "flyte-binary.renderTemplate" (dict "value" .Values.rbac.annotations "context" $) | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
      - ""
  resources:
      - namespaces
      - resourcequotas
      - secrets
  verbs:
      - create
      - get
      - list
      - patch
      - update
- apiGroups:
      - ""
  resources:
      - pods
  verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
- apiGroups:
      - ""
  resources:
      - events
  verbs:
      - create
      - delete
      - patch
      - update
- apiGroups:
      - flyte.lyft.com
  resources:
      - flyteworkflows
  verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - post
      - update
      - watch
- apiGroups:
      - apiextensions.k8s.io
  resources:
      - customresourcedefinitions
  verbs:
      - create
      - get
      - list
- apiGroups:
      - admissionregistration.k8s.io
  resources:
      - mutatingwebhookconfigurations
  verbs:
      - create
      - get
      - list
      - patch
      - update
{{- end }}
