{{- if and .Values.configuration.database.password (not .Values.configuration.externalConfigMap) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flyte-binary.configuration.database.passwordSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{ include "flyte-binary.configuration.database.passwordSecretMountPath" . | base }}: {{ .Values.configuration.database.password | quote }}
{{- end }}
