apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flyte-role
rules:
- apiGroups:
      - ""
  resources:
      - namespaces
      - resourcequotas
      - secrets
  verbs:
      - create
      - get
      - list
      - patch
      - update
- apiGroups:
      - ""
  resources:
      - pods
  verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
- apiGroups:
      - ""
  resources:
      - events
  verbs:
      - create
      - delete
      - patch
      - update
- apiGroups:
      - flyte.lyft.com
  resources:
      - flyteworkflows
  verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - post
      - update
      - watch
- apiGroups:
      - apiextensions.k8s.io
  resources:
      - customresourcedefinitions
  verbs:
      - create
      - get
      - list
- apiGroups:
      - admissionregistration.k8s.io
  resources:
      - mutatingwebhookconfigurations
  verbs:
      - create
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flyte-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flyte-role
subjects:
  - kind: ServiceAccount
    name: flyte
    # Have to add a namespace explicitly here so that the generated manifest has it
    # since kubectl apply --namespace won't update it.
    namespace: {{ .Release.Namespace }}
