apiVersion: v1
kind: Service
metadata:
  name: flyte
spec:
  ports:
    - name: http
      port: 8088
    - name: grpc
      port: 8089
    - name: webhook
      port: 443
      targetPort: 9443
  selector:
    app: flyte
