apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyte-sandbox.fullname" . }}
  labels:
    {{- include "flyte-sandbox.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    {{- include "flyte-sandbox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
