propeller:
  rawoutput-prefix: s3://flyte-outputs
  metadata-prefix: propeller/eks
  workers: 4
  max-workflow-retries: 30
  workflow-reeval-duration: 30s
  downstream-eval-duration: 30s
  limit-namespace: "all"
  prof-port: 10254
  metrics-prefix: flyte
  enable-admin-launcher: true
  leader-election:
    lock-config-map:
      name: propeller-leader
      namespace: flyte
    enabled: true
    lease-duration: 15s
    renew-deadline: 10s
    retry-period: 2s
  queue:
    type: batch
    batching-interval: 2s
    batch-size: -1
    queue:
      type: bucket
      rate: 10
      capacity: 100
    sub-queue:
      type: bucket
      rate: 10
      capacity: 100
  resourcemanager:
    type: redis
    resourceMaxQuota: 10000
    redis:
      hostPath: redis-resource-manager.flyte:6379
      hostKey: mypassword
logger:
  show-source: true
  level: 5
storage:
  type: s3
  connection:
    auth-type: iam
    region: us-west-2
  cache:
    max_size_mbs: 1024
    target_gc_percent: 70
  container: "flyte-metadata"
  limits:
    maxDownloadMBs: 10
event:
  type: admin
  rate: 500
  capacity: 1000
admin:
  endpoint: flyteadmin:81
  insecure: true
catalog-cache:
  endpoint: datacatalog:89
  type: datacatalog
  insecure: true
tasks:
  task-plugins:
    enabled-plugins:
      - container
      - sidecar
      - k8s-array
