apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flyte-sandbox.fullname" . }}-proxy
  labels:
    {{- include "flyte-sandbox.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "flyte-sandbox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        {{- include "flyte-sandbox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: proxy
    spec:
      containers:
        - name: proxy
          image: envoyproxy/envoy:v1.23-latest
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
      volumes:
        - name: config
          configMap:
            name: {{ include "flyte-sandbox.fullname" . }}-proxy-config
