{{- if .Values.common.ingress.enabled }}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "flyte.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  {{- with .Values.common.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  ingressClassName: {{ .Values.common.ingress.ingressClassName | quote }}
  rules:
    - http:
        paths:
          {{- if .Values.common.ingress.albSSLRedirect }}
          - path: /*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
              {{- else }}
              serviceName: ssl-redirect
              servicePort: use-annotation
              {{- end }}
          {{- end }}
          # This is useful only for frontend development
          {{- if .Values.common.ingress.webpackHMR }}
          - path: /__webpack_hmr
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteconsole
                port:
                  number: 80
              {{- else }}
              serviceName: flyteconsole
              servicePort: 80
              {{- end }}
          {{- end }}
          # NOTE: If you change this, you must update the BASE_URL value in flyteconsole.yaml
          - path: /console
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteconsole
                port:
                  number: 80
              {{- else }}
              serviceName: flyteconsole
              servicePort: 80
              {{- end }}
          - path: /console/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteconsole
                port:
                  number: 80
              {{- else }}
              serviceName: flyteconsole
              servicePort: 80
              {{- end }}
          - path: /api
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /healthcheck
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /v1/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          {{- if .Values.deployRedoc }}
          # Port 87 in FlyteAdmin maps to the redoc container.
          - path: /openapi
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: redoc
                port:
                  number: 87
              {{- else }}
              serviceName: redoc
              servicePort: 87
              {{- end }}
          # Port 87 in FlyteAdmin maps to the redoc container.
          - path: /openapi/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: redoc
                port:
                  number: 87
              {{- else }}
              serviceName: redoc
              servicePort: 87
              {{- end }}
          {{- end }}
          - path: /.well-known
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /.well-known/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /login
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /login/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /logout
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /logout/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /callback
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /callback/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /me
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /config
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /config/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /oauth2
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          - path: /oauth2/*
            pathType: ImplementationSpecific
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: flyteadmin
                port:
                  number: 80
              {{- else }}
              serviceName: flyteadmin
              servicePort: 80
              {{- end }}
          {{- if not .Values.common.ingress.separateGrpcIngress }}
          {{- include "ingress.grpcRoutes" . | nindent 10 -}}
          {{- end }}
      host: {{ tpl (toYaml .Values.common.ingress.host) $ }}
  {{- if .Values.common.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.common.ingress.tls.secretName | default (printf "%s-flyte-tls" .Release.Name) }}
      hosts:
        - {{ tpl (toYaml .Values.common.ingress.host) $ }}
  {{ end }}
{{- end }}
