{{- if or .Values.flytepropeller.enabled .Values.flytescheduler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: flyte-secret-auth
  namespace: {{ template "flyte.namespace" . }}
type: Opaque
stringData:
  client_secret: {{ .Values.adminOauthClientCredentials.client_secret }}
{{- end }}
