# ClusterRole for flyteadmin
# https://kubernetes.io/docs/admin/authorization/rbac/
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flyteadmin
  namespace: flyte
rules:
#Allow Access to all resources under flyte.lyft.com and the core API group: "" 
 - apiGroups:
   - ""
   - flyte.lyft.com
   - rbac.authorization.k8s.io
   resources:
   - configmaps
   - flyteworkflows
   - namespaces
   - pods
   - resourcequotas
   - roles
   - rolebindings 
   - secrets
   - services
   - serviceaccounts
   - spark-role
   verbs:
   - "*"

---
# Create a Service Account for FltyeAdmin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flyteadmin
  namespace: flyte

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flyteadmin-binding
  namespace: flyte
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flyteadmin
subjects:
  - kind: ServiceAccount
    name: flyteadmin
    namespace: flyte
