---
# Source: flyte-binary/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flyte-flyte-binary
  namespace: "flyte"
  labels:
    helm.sh/chart: flyte-binary-0.1.0
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
---
# Source: flyte-binary/templates/cluster-resource-templates.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-flyte-binary-cluster-resource-templates
  namespace: "flyte"
  labels:
    helm.sh/chart: flyte-binary-0.1.0
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
data:
  namespace.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: '{{ namespace }}'
---
# Source: flyte-binary/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-flyte-binary-config
  namespace: "flyte"
  labels:
    helm.sh/chart: flyte-binary-0.1.0
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
data:
  000-core.yaml: |
    admin:
      endpoint: localhost:8089
      insecure: true
    catalog-cache:
      endpoint: localhost:8081
      insecure: true
      type: datacatalog
    cluster_resources:
      standaloneDeployment: false
      templatePath: /etc/flyte/cluster-resource-templates
    logger:
      show-source: true
      level: 1
    propeller:
      create-flyteworkflow-crd: true
    webhook:
      certDir: /var/run/flyte/certs
      localCert: true
      secretName: flyte-flyte-binary-webhook-secret
      serviceName: flyte-flyte-binary-webhook
      servicePort: 443
  001-plugins.yaml: |
    tasks:
      task-plugins:
        enabled-plugins:
          - container
          - sidecar
          - K8S-ARRAY
        default-for-task-types:
          - container: container
          - container_array: K8S-ARRAY
    plugins:
      logs:
        
      k8s-array:
        logs:
          config:
            
  002-database.yaml: |
    database:
      postgres:
        username: postgres
        passwordPath: 
        host: 127.0.0.1
        port: 5432
        dbname: flyte
        options: "sslmode=disable"
  003-storage.yaml: |
    propeller:
      rawoutput-prefix: s3://my-organization-flyte-container/data
    storage:
      type: s3
      connection:
        region: us-east-1
        disable-ssl: false
        auth-type: "iam"
      container: my-organization-flyte-container
---
# Source: flyte-binary/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flyte-flyte-binary-cluster-role
  namespace: "flyte"
  labels:
    helm.sh/chart: flyte-binary-0.1.0
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
rules:
- apiGroups:
      - ""
  resources:
      - namespaces
      - resourcequotas
      - secrets
  verbs:
      - create
      - get
      - list
      - patch
      - update
- apiGroups:
      - ""
  resources:
      - pods
  verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
- apiGroups:
      - ""
  resources:
      - events
  verbs:
      - create
      - delete
      - patch
      - update
- apiGroups:
      - flyte.lyft.com
  resources:
      - flyteworkflows
  verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - post
      - update
      - watch
- apiGroups:
      - apiextensions.k8s.io
  resources:
      - customresourcedefinitions
  verbs:
      - create
      - get
      - list
- apiGroups:
      - admissionregistration.k8s.io
  resources:
      - mutatingwebhookconfigurations
  verbs:
      - create
      - get
      - list
      - patch
      - update
---
# Source: flyte-binary/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flyte-flyte-binary-cluster-role-binding
  namespace: "flyte"
  labels:
    helm.sh/chart: flyte-binary-0.1.0
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flyte-flyte-binary-cluster-role
subjects:
  - kind: ServiceAccount
    name: flyte-flyte-binary
    namespace: "flyte"
---
# Source: flyte-binary/templates/service/main.yaml
apiVersion: v1
kind: Service
metadata:
  name: flyte-flyte-binary
  namespace: "flyte"
  labels:
    helm.sh/chart: flyte-binary-0.1.0
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 8088
      targetPort: http
      nodePort: null
    - name: grpc
      port: 8089
      targetPort: grpc
      nodePort: null
  selector:
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
---
# Source: flyte-binary/templates/service/webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: flyte-flyte-binary-webhook
  namespace: "flyte"
  labels:
    helm.sh/chart: flyte-binary-0.1.0
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
  selector:
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
---
# Source: flyte-binary/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyte-flyte-binary
  namespace: "flyte"
  labels:
    helm.sh/chart: flyte-binary-0.1.0
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/instance: flyte
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: flyte-binary
      app.kubernetes.io/instance: flyte
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flyte-binary
        app.kubernetes.io/instance: flyte
      annotations:
        checksum/configuration: e353e8eeef9f7c15de463039962283149249e68463b63e530683f183d4afe5e6
        checksum/cluster-resource-templates: 107623522504d692aadc02559747bc8dd8e66095b46f0c17d6ebd0d8957cb089
    spec:
      serviceAccountName: flyte-flyte-binary
      initContainers:
        - name: wait-for-db
          image: "postgres:15-alpine"
          imagePullPolicy: "IfNotPresent"
          command:
            - sh
            - -ec
          args:
            - |
              until pg_isready \
                -h 127.0.0.1 \
                -p 5432 \
                -U postgres
              do
                echo waiting for database
                sleep 0.1
              done
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 1
      containers:
        - name: flyte
          image: "ghcr.io/flyteorg/flyte-sandbox:flytebinary_1007"
          imagePullPolicy: "IfNotPresent"
          args:
            - start
            - --config
            - /etc/flyte/config.d/*.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8088
            - name: grpc
              containerPort: 8089
            - name: webhook
              containerPort: 9443
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 1
          volumeMounts:
            - name: cluster-resource-templates
              mountPath: /etc/flyte/cluster-resource-templates
            - name: config
              mountPath: /etc/flyte/config.d
            - name: state
              mountPath: /var/run/flyte
      volumes:
        - name: cluster-resource-templates
          configMap:
            name: flyte-flyte-binary-cluster-resource-templates
        - name: config
          configMap:
            name: flyte-flyte-binary-config
        - name: state
          emptyDir: {}
