{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flyte-binary.fullname" . }}-http
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "flyte-binary.renderTemplate" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.labels }}
    {{- include "flyte-binary.renderTemplate" (dict "value" .Values.ingress.labels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "flyte-binary.renderTemplate" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "flyte-binary.renderTemplate" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /console
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /console/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /api
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /api/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /healthcheck
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /v1/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /.well-known
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /.well-known/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /login
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /login/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /logout
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /logout/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /callback
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /callback/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /me
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /config
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /config/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /oauth2
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.fullname" . }}
            port:
              number: {{ include "flyte-binary.service.httpPort" . }}
        path: /oauth2/*
        pathType: ImplementationSpecific
    {{- if .Values.ingress.host }}
    host: {{ include "flyte-binary.renderTemplate" ( dict "value" .Values.ingress.host "context" $ ) }}
    {{- end }}
{{- end }}
