# Create the actual deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyteconsole
  namespace: flyte
  labels:
    app: flyteconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyteconsole
  template:
    metadata:
      labels:
        app: flyteconsole
        app.kubernetes.io/name: flyteconsole
        app.kubernetes.io/version: 0.19.0
    spec:
      securityContext:
        runAsUser: 1000
        fsGroupChangePolicy: "Always"
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: flyteconsole
        image: flyteconsole:v0.19.0
        # args: []
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shared-data
          mountPath: /srv/flyte
        envFrom:
        - configMapRef:
           name: flyte-console-config
