# Service
apiVersion: v1
kind: Service
metadata:
  name: contour
  labels:
    app: contour
spec:
  # use NodePort to make sure the service is accessible
  type: NodePort
  selector:
    app: contour
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30081
