logger:
  show-source: true
  level: 5
datacatalog:
  storage-prefix: metadata/datacatalog
  metrics-scope: "datacatalog"
  profiler-port: 10254
application:
  grpcPort: 8089
database:
  port: 5432
  username: flyteadmin
  host: flyteadmin-cluster.cluster-456123e6ivib.us-west-2.rds.amazonaws.com
  dbname: flytedatacatalog
  password: spongebob
storage:
  type: s3
  connection:
    auth-type: iam
    region: us-west-2
  cache:
    max_size_mbs: 64
    target_gc_percent: 70
  container: "flyte-datacatalog"

