apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyte-binary.webhook.serviceName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "flyte-binary.renderTemplate" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.service.labels }}
    {{- include "flyte-binary.renderTemplate" (dict "value" .Values.service.labels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "flyte-binary.renderTemplate" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- include "flyte-binary.renderTemplate" (dict "value" .Values.service.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
  selector: {{- include "flyte-binary.selectorLabels" . | nindent 4 }}
