name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      component:
        description: "Flyte component name"
        required: true
        type: string
      dockerfile:
        description: "Dockerfile"
        required: true
        type: string
      push:
        description: "Whether to push built image to registry"
        required: true
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  push-github:
    name: Build and Push Image To ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::558384610515:role/github-actions-flyte-fork
          aws-region: us-east-1 # public ECR is only available in us-east-1
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Prepare Image Tags
        id: tags
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.ecr-login.outputs.registry }}/p6w6o0n4/${{ inputs.component }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
            type=raw,value=${{ github.event.pull_request.head.sha || github.sha }}
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: linux/arm64,linux/amd64
          push: ${{ inputs.push }}
          tags: ${{ steps.tags.outputs.tags }}
