name: Build & Publish All Images

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  # for master branch we want every commit to have corresponding images
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  single-binary:
    uses: ./.github/workflows/single-binary.yml
  components:
    uses: ./.github/workflows/create_release.yml
    needs: single-binary
  sandbox:
    uses: ./.github/workflows/sandbox.yml
    needs: single-binary
