name: Build & Push All Component Docker Images

on:
  workflow_call:
    inputs:
      push:
        description: "Whether to push built images to registry"
        required: true
        type: boolean

jobs:
  push_docker_image:
    strategy:
      fail-fast: false
      matrix:
        component:
          - datacatalog
          - flyteadmin
          - flytecopilot
          - flytepropeller
          - flytescheduler
    uses: ./.github/workflows/build-and-push-docker-image.yml
    with:
      component: ${{ matrix.component }}
      dockerfile: Dockerfile.${{ matrix.component }}
      push: ${{ inputs.push }}
