name: Components Checks

on:
  pull_request:
  push:
    branches:
      - master
env:
  GO_VERSION: "1.19"
  PRIORITIES: "P0"
jobs:
  unpack-envvars:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.step.outputs.go-version }}
    steps:
      - id: step
        run: |
          echo "go-version=${{ env.GO_VERSION }}" >> $GITHUB_OUTPUT

  # lint:
  #   name: Lint
  #   uses: flyteorg/flytetools/.github/workflows/lint.yml@master
  #   with:
  #     go-version: "1.19"

  # tests:
  #   name: Unit Tests
  #   uses: flyteorg/flytetools/.github/workflows/tests.yml@master
  #   with:
  #     go-version: "1.19"
  #   secrets:
  #     FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
  docker-build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - datacatalog
          - flyteadmin
          - flytecopilot
          - flytepropeller
    name: Docker Build Images
    uses: ./.github/workflows/component_docker_build.yml
    with:
       component: ${{ matrix.component }}

  # TODO(monorepo): these tests are broken. They never test an actual change.
  # endtoend:
  #   name: End2End Test
  #   needs: [ docker-build ]
  #   uses: ./.github/workflows/end2end.yml
  #   with:
  #     # Reusing the output of the matrix is ok as they are essentially writing the same value (i.e. the directory artifacts are written + run id)
  #     cache_key: ${{ needs.docker-build.outputs.cache_key }}
  #     priorities: "P0"

  integration:
    name: Integration Test
    needs:
      - docker-build
      - unpack-envvars
    strategy:
      fail-fast: false
      matrix:
        component:
          - flyteadmin
          - flytepropeller
    uses: ./.github/workflows/integration.yml
    with:
      component: ${{ matrix.component }}
      cache_key: ${{ needs.docker-build.outputs.cache_key }}
      go-version: ${{ needs.unpack-envvars.outputs.go-version }}

  generate:
    name: Check Go Generate
    needs:
      - unpack-envvars
    strategy:
      fail-fast: false
      matrix:
        component:
          - datacatalog
          - flyteadmin
          - flytecopilot
          - flytepropeller
    uses: ./.github/workflows/go_generate.yml
    with:
      component: ${{ matrix.component }}
      go-version: ${{ needs.unpack-envvars.outputs.go-version }}

  # bump_version:
  #   name: Bump Version
  #   if: ${{ github.event_name != 'pull_request' }}
  #   needs: [ endtoend,  integration, lint, tests, generate ] # Only to ensure it can successfully build
  #   uses: flyteorg/flytetools/.github/workflows/bump_version.yml@master
  #   secrets:
  #     FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  # goreleaser:
  #   name: Goreleaser
  #   needs: [ bump_version ] # Only to ensure it can successfully build
  #   uses: flyteorg/flytetools/.github/workflows/goreleaser.yml@master
  #   with:
  #     go-version: "1.19"
  #   secrets:
  #     FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  # push_docker_image:
  #   name: Build & Push Flytepropeller Image
  #   needs: [ bump_version ]
  #   uses: flyteorg/flytetools/.github/workflows/publish.yml@master
  #   with:
  #     version: ${{ needs.bump_version.outputs.version }}
  #     dockerfile: Dockerfile
  #     push: true
  #     repository: ${{ github.repository }}
  #   secrets:
  #     FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
  #     FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}

  # TODO(monorepo): push flytescheduler image
  # push-docker-image-flytescheduler:
  #   name: Build & Push Flytescheduler Image
  #   needs: [ bump_version ]
  #   uses: flyteorg/flytetools/.github/workflows/publish.yml@master
  #   with:
  #     version: ${{ needs.bump_version.outputs.version }}
  #     push: true
  #     repository: flyteorg/flytescheduler
  #     dockerfile: scheduler.Dockerfile
  #   secrets:
  #     FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
  #     FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}
