name: Contributors

on:
  # schedule:
  #   - cron: '0 12 * * 1' # At 12 noon on Monday.
  push:
    branches: 
      - contributors-action

jobs:
  contributors:
    runs-on: ubuntu-latest
    if: ${{ !startsWith( github.event.head_commit.message , '[auto-update-contributors]' ) }}
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Contributors Action
        uses: hyperledger-tooling/github-contributors-action@v0.0.1
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SOURCE_GITHUB_REPOSITORY: flyteorg/flyte
          CONTRIBUTORS_SECTION_PATTERN: <!-- CONTRIBUTORS START -->
          CONTRIBUTORS_SECTION_END_PATTERN: <!-- CONTRIBUTORS END -->
          INPUT_TEMPLATE_FILE: ./assets/contributor-template.md
          FILE_WITH_PATTERN: ./README.md
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          commit-message: '[auto-update-contributors] update all-contributors'
          committer: Flyte-Bot <admin@flyte.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: flyte-bot-update-releases
          delete-branch: true
          title: 'auto-update contributors'
          labels: contibutors
          team-reviewers: |
            owners
            maintainers
          draft: false
