name: Contributors
on: push
# jobs:
#   add-contributors:
#     runs-on: ubuntu-latest
#     # only run if the commit wasn't created by the auto-contrib-bot
#     if: ${{ !startsWith( github.event.head_commit.message , '[auto-contrib-bot]' ) }}
#     steps:
#     - uses: actions/checkout@v2
#     - uses: BobAnkh/add-contributors@v0.2.2
#       with:
#         ACCESS_TOKEN: ${{secrets.FLYTE_BOT_PAT}}
#         CONTRIBUTOR: '<!-- Flyte Contributors -->'
#         COLUMN_PER_ROW: '8'
#         IMG_WIDTH: '90'
#         FONT_SIZE: '10'
#         PATH: '/README.md'
#         BRANCH: ${{ github.ref }}
#         COMMIT_MESSAGE: '[auto-contrib-bot] update contributors'
#         AVATAR_SHAPE: round

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}
          svgPath: ./CONTRIBUTORS.svg
          noCommit: true
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          commit-message: Update CONTRIBUTORS.svg
          committer: Flyte-Bot <admin@flyte.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: flyte-bot-update-releases
          delete-branch: true
          title: 'Update contributors'
          labels: contibutors
          team-reviewers: |
            owners
            maintainers
          draft: false
