name: Test Flyte Release

on:
  workflow_dispatch:
    inputs:
      priority:
        description: 'priority for e2e test'
        required: true
        default: 'all'
jobs:
  deploy:
    strategy:
      matrix:
        RUNNER: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{matrix.RUNNER}}
    steps:
      - uses: actions/checkout@v2
      - name: Create Cluster
        run: |
          bash ./script/e2e_test.sh ${{matrix.RUNNER}} ${{ github.event.inputs.priority }}
        shell: bash