name: Flytectl checks

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "boilerplate/**"

jobs:
  dry_run_goreleaser:
    name: Dry Run Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: "0"
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Run GoReleaser dry run
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: latest
          args: --snapshot  --skip-publish --rm-dist -f flytectl/.goreleaser.yml
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
