name: Build & Push All Components Images

on:
  workflow_call:
    inputs:
      push:
        description: "Push to registry"
        required: true
        type: boolean

jobs:
  push_docker_image:
    name: Build & Push Image
    strategy:
      fail-fast: false
      matrix:
        component:
          - datacatalog
          - flyteadmin
          - flytecopilot
          - flytepropeller
          - flytescheduler
    uses: ./.github/workflows/publish.yml
    with:
      component: ${{ matrix.component }}
      dockerfile: Dockerfile.${{ matrix.component }}
      push: ${{ inputs.push }}
