name: Publish flyte defination file

on: 
  workflow_dispatch:

jobs:
  update-flyte-releases:
    name: Update Flyte components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build kustomize
        run: |
          make release_automation
          make kustomize
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          commit-message: Update Flyte Components
          committer: Flyte-Bot <admin@flyte.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: flyte-bot-update-releases
          delete-branch: true
          title: 'Update Flyte components'
          body: |
            Updated flyte deployment
            - Updated GCP Flyte deployment
            - Updated EKS Flyte deployment
            - Updated Sandbox Flyte deployment
            - Updated TEST Flyte deployment
            - Auto-generated by [flyte-bot]
          labels: |
            kustomize
          team-reviewers: |
            owners
            maintainers
          draft: false