name: Build & Push Sandbox Docker Image

on:
  # push:
  pull_request:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Sandbox image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64, linux/amd64
          push: true
          target: dind
          tags: avaneeshy/flyte-sandbox:latest
          file: docker/sandbox/Dockerfile
          cache-from: type=local, src=docker-cache
          cache-to: type=inline, type=local, dest=docker-cache
      - name: Build and push DIND Image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64, linux/amd64
          push: true
          target: dind
          tags: avaneeshy/flyte-sandbox:dind
          file: docker/sandbox/Dockerfile
          cache-from: type=local, src=docker-cache
          cache-to: type=inline, type=local, dest=docker-cache
          # TODO: explore caching to CI # https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
