name: Build & Push Sandbox Docker Image

on:
  pull_request:
  create:
    tags:
      - v*

jobs:
  push-github:
    name: Push to GHCR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Push Sandbox Plugin Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          # https://docs.github.com/en/packages/learn-github-packages/publishing-a-package
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
          image_name: ${{ github.repository_owner }}/flyte-sandbox
          image_tag: latest,${{ github.sha }},${{ github.event.ref }}
          push_git_tag: true
          registry: ghcr.io
          build_extra_args: "--target=default --compress=true"
          context: ./deployment/sandbox
          dockerfile: docker/Dockerfile
      - name: Push Sandbox Plugin DIND Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
          image_name: ${{ github.repository_owner }}/flyte-sandbox
          image_tag: dind,${{ github.sha }},${{ github.event.ref }}
          push_git_tag: true
          registry: ghcr.io
          build_extra_args: "--target=dind --compress=true"
          context: ./deployment/sandbox
          dockerfile: docker/Dockerfile
