name: tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"
      - name: Compile
        run: make compile
      - name: Run tests
        run: make test_unit

  generate_kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.21"
      - name: Kustomize and diff
        run: DELTA_CHECK=true make kustomize

  generate_helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.21"
      - name: Helm and diff
        run: DELTA_CHECK=true make helm
