name: tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f doc-requirements.txt ]; then pip install -r doc-requirements.txt; fi
      - name: Build the documentation
        run: make docs

  end-to-end-kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Kustomize and diff
        run: DELTA_CHECK=true make kustomize
      - name: Helm and diff
        run: DELTA_CHECK=true make helm
      - uses: engineered/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: End2End
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          # launch flyte end2end
          kubectl apply -f "./deployment/test/flyte_generated.yaml"
          make end2end_execute

  end-to-end-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Kustomize and diff
        run: DELTA_CHECK=true make kustomize
      - name: Helm and diff
        run: DELTA_CHECK=true make helm
      - uses: engineered/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: End2End
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          # launch flyte end2end
          make helm_update
          make helm_install
          make end2end_execute
