name: Unit Tests

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      go-version:
        required: true
        type: string
    secrets:
      FLYTE_BOT_PAT:
        required: true
jobs:
  tests:
    name: Run Unit Test
    defaults:
      run:
        working-directory: ${{ inputs.component }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      - name: Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}
        run: make install && make test_unit_codecov
      # TODO(monorepo): Figure out how to do code coverage aggregation
      - name: Push CodeCov
        uses: codecov/codecov-action@v3.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: false
